{{- if .Values.initCluster -}}
{{- $name := include "stolon.fullname" . | printf "%s-init-cluster" | trunc 63 | trimSuffix "-" -}}
{{- $annotaions := dict -}}
{{- $_ := set $annotaions "helm.sh/hook" "post-install" -}}
{{- $_ := set $annotaions "helm.sh/hook" "before-hook-creation,hook-succeeded" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
  annotations:
    {{ toYaml $annotaions | indent 4 | trim }}
data:
  spec.json: |
    {{- toJson .Values.clusterSpec | nindent 4 }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $name }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
  annotations:
    {{ toYaml $annotaions | indent 4 | trim }}
spec:
  containers:
    - name: init-cluster
      image: {{ include "stolon.stolonctl.image" . | quote }}
      args:
        - --cluster-name
        - {{ .Values.clusterName }}
        - init
        - --yes
        - --file
        - /config/spec.json
      securityContext:
        {{- toYaml .Values.keeper.securityContext | nindent 8 }}
      volumeMounts:
        - name: config
          mountPath: /config
  volumes:
    - name: config
      configMap:
        name: {{ $name }}
  restartPolicy: Never
  serviceAccountName: {{ include "stolon.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.keeper.podSecurityContext | nindent 4 }}
{{- end -}}
