{{- if .Values.updateClusterSpec -}}
{{- $name := include "stolon.fullname" . | printf "%s-update-cluster-spec" | trunc 63 | trimSuffix "-" -}}
{{- $annotations := dict -}}
{{- $_ := set $annotations "helm.sh/hook" "post-upgrade" -}}
{{- $_ := set $annotations "helm.sh/hook-weight" "20" -}}
{{- $_ := set $annotations "helm.sh/hook-delete-policy" "before-hook-creation" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
  annotations:
    {{ toYaml $annotations | indent 4 | trim }}
data:
  spec.json: |
    {{- toJson .Values.clusterSpec | nindent 4 }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $name }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
  annotations:
    {{ toYaml $annotations | indent 4 | trim }}
spec:
  initContainers:
    - name: update-cluster-spec
      image: {{ include "stolon.stolonctl.image" . | quote }}
      args:
        - --cluster-name
        - {{ .Values.clusterName }}
        - update
        - --file
        - /config/spec.json
      {{- if .Values.stolonctl.extraEnvVars }}
      env:
        {{- range .Values.stolonctl.extraEnvVars }}
        - {{ toYaml . | indent 10 | trim }}
        {{- end }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.keeper.securityContext | nindent 8 }}
      volumeMounts:
        - name: config
          mountPath: /config
        {{- range .Values.stolonctl.extraVolumeMounts }}
        - {{ toYaml . | indent 10 | trim }}
        {{- end }}
  containers:
    - name: get-cluster-spec
      image: {{ include "stolon.stolonctl.image" . | quote }}
      args:
        - --cluster-name
        - {{ .Values.clusterName }}
        - spec
      {{- if .Values.stolonctl.extraEnvVars }}
      env:
        {{- range .Values.stolonctl.extraEnvVars }}
        - {{ toYaml . | indent 10 | trim }}
        {{- end }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.keeper.securityContext | nindent 8 }}
      volumeMounts:
        - name: config
          mountPath: /config
        {{- range .Values.stolonctl.extraVolumeMounts }}
        - {{ toYaml . | indent 10 | trim }}
        {{- end }}
  volumes:
    - name: config
      configMap:
        name: {{ $name }}
    {{- range .Values.stolonctl.extraVolumes }}
    - {{ toYaml . | indent 6 | trim }}
    {{- end }}
  restartPolicy: Never
  serviceAccountName: {{ include "stolon.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.keeper.podSecurityContext | nindent 4 }}
{{- end -}}
