{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "stolon.rbacName" . }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
rules:
  {{- range $_, $rule := .Values.rbac.rules }}
  - {{ toYaml $rule | indent 4 | trim }}
  {{- end }}
{{- end -}}
