apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stolon.fullname" . }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
type: Opaque
data:
  pg-su-username: {{ .Values.suUsername | b64enc }}
  pg-su-password: {{ .Values.suPassword | b64enc }}
  pg-repl-username: {{ .Values.replUsername | b64enc }}
  pg-repl-password: {{ .Values.replPassword | b64enc }}
