apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stolon.fullname" . }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
type: Opaque
data:
  pg-host: {{ printf "%s.%s.svc.%s" (include "stolon.proxy.serviceName" .) (.Release.Namespace) (toString .Values.clusterSuffix | trimAll ".") | b64enc }}
  pg-port: {{ .Values.proxy.service.port | int | toString | b64enc }}
  pg-su-username: {{ .Values.suUsername | b64enc }}
  pg-su-password: {{ .Values.suPassword | b64enc }}
  pg-repl-username: {{ .Values.replUsername | b64enc }}
  pg-repl-password: {{ .Values.replPassword | b64enc }}
