{{- if or .Values.sentinel.metrics.enabled .Values.proxy.metrics.enabled .Values.keeper.metrics.enabled -}}
{{-   if and .Values.serviceMonitor.create (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1")  -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "stolon.serviceMonitorName" .}}
  namespace: {{ default .Release.Namespace .Values.serviceMonitor.namespace }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
spec:
  attachMetadata:
    node: false
  endpoints:
    - port: metrics
      scheme: http
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- if .Values.serviceMonitor.relabelings }}
      relabelings:
        {{ toYaml .Values.serviceMonitor.relabelings | indent 8 | trim }}
      {{- end }}
      {{- if .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{ toYaml .Values.serviceMonitor.metricRelabelings | indent 8 | trim }}
      {{- end }}
  jobLabel: {{ .Values.serviceMonitor.jobLabel }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      {{- include "stolon.selectorLabels" . | nindent 6 }}
{{-   end -}}
{{- end -}}
