apiVersion: v1
kind: Service
metadata:
  name: {{ include "stolon.keeper.serviceName" . }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
    app.kubernetes.io/component: keeper
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.keeper.containerPort }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "stolon.keeper.selectorLabels" . | nindent 4 }}
