apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stolon.proxy.name" . }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  {{- if not .Values.proxy.autoscaling.enabled }}
  replicas: {{ .Values.proxy.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "stolon.proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.proxy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stolon.proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stolon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.proxy.podSecurityContext | nindent 8 }}
      containers:
        - name: proxy
          securityContext:
            {{- toYaml .Values.proxy.securityContext | nindent 12 }}
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          env:
            {{- include "stolon.commonEnv" . | nindent 12 }}
            - name: STPROXY_CLUSTER_NAME
              value: {{ .Values.clusterName | quote }}
          ports:
            - name: postgres
              containerPort: {{ .Values.proxy.containerPort }}
              protocol: TCP
            {{- if .Values.proxy.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.proxy.metrics.port }}
              protocol: TCP
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: postgres
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
      {{- with .Values.proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
