apiVersion: v1
kind: Service
metadata:
  name: {{ include "stolon.proxy.serviceName" . }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "stolon.proxy.selectorLabels" . | nindent 4 }}
